### PR TITLE
Ming branch

### PR DESCRIPTION
**Pull request by daimingzhong**
modify readme

### CODE REVIEW

**Comment by Nevvea7** [comment]
hey are you a member of cssa? do you want to take the ownership of the organization?

**Comment by yl2193** [comment]
Yo Anna~

**Comment by Nevvea7** [comment]
yo long time no see

**Comment by YichenGong** [comment]
daimingzhong is the current leader of CSSA web department. Authorize him please, Anna!

**Comment by daimingzhong** [comment]
Yo Yichen~

**Comment by daimingzhong** [comment]
Hello, Anna. Glad to know you!

**Comment by yl2193** [comment]
Oh we have a web department now. That's a huge step LOL. Cheers

**Comment by daimingzhong** [comment]
Yeah. We have 6 more members this year!! Trying to make big news. lol

**Comment by Nevvea7** [comment]
That's great news! keep up the good work 🎈

**Comment by daimingzhong** [comment]
Thanks, Anna. I will add more members from cssa tech team to this repo.

**Pull request closed without merging**
